<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<script>
    //1,,,

//    try {
//        console.log(i);
//    }catch(e){
//
//    }
//    console.log('over');//这时会输出over，是运行时的错误，语法解析的时候是没有错误的

    //2...

    try {
       var arr = [;];
    }catch(e){

    }
    console.log('over');
    //语法错误，在预解析的时候发生了错误，而异常时在执行的过程中处理





</script>
</body>
</html>